/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Ali
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMainlabel = new javax.swing.JLabel();
        jFirstNameLablel = new javax.swing.JLabel();
        jLastNameLabel = new javax.swing.JLabel();
        jAgeLabel = new javax.swing.JLabel();
        jEmailLabel = new javax.swing.JLabel();
        jFirstNametext = new javax.swing.JTextField();
        jLastNameText = new javax.swing.JTextField();
        jAgeText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jMainlabel.setBackground(new java.awt.Color(0, 0, 0));
        jMainlabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMainlabel.setForeground(new java.awt.Color(255, 255, 255));
        jMainlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainlabel.setText("Customer Registration Form");
        jMainlabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jFirstNameLablel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jFirstNameLablel.setForeground(new java.awt.Color(255, 255, 255));
        jFirstNameLablel.setText("FirstName:");

        jLastNameLabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLastNameLabel.setText("LastName:");

        jAgeLabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        jAgeLabel.setText("Age:");

        jEmailLabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        jEmailLabel.setText("Email:");

        jFirstNametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNametextActionPerformed(evt);
            }
        });

        jEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailTextActionPerformed(evt);
            }
        });

        jSubmitButton.setBackground(new java.awt.Color(204, 204, 204));
        jSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSubmitButton.setText("Submit");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jMainlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jEmailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jAgeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jFirstNameLablel)
                                .addGap(59, 59, 59)
                                .addComponent(jFirstNametext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jMainlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameLablel)
                    .addComponent(jFirstNametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgeLabel)
                    .addComponent(jAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailLabel)
                    .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jSubmitButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFirstNametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNametextActionPerformed

    private void jEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailTextActionPerformed

    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        // TODO add your handling code here:
        String First_name = jFirstNametext.getText();
        String age = jAgeText.getText();
        String Last_name = jLastNameText.getText();
        String Email = jEmailText.getText();
            if (!First_name.isEmpty() && !Last_name.isEmpty() && !age.isEmpty()&& !Email.isEmpty()) {
        // Create and display a dialog box to show name and age
        System.out.println(First_name+" "+Last_name+" "+age+" "+Email   );
        String message = "First Name: " + First_name + "\nLast Name: " + Last_name  + "\nAge: " + age + "\nEmail: "+Email;
                JOptionPane.showMessageDialog(this, message, "User Info", JOptionPane.INFORMATION_MESSAGE);
    } 
            else if(Email.isEmpty() && First_name.isEmpty() && Last_name.isEmpty() && age.isEmpty()){
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter your First Name.\nPlease enter your Last Name.\nPlease enter your Age.\nPlease enter your Email.", "Error", JOptionPane.ERROR_MESSAGE);
    }
                        else if(Email.isEmpty() && !First_name.isEmpty() && Last_name.isEmpty() && age.isEmpty()){
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter your Last Name.\nPlease enter your Age.\nPlease enter your Email.", "Error", JOptionPane.ERROR_MESSAGE);
    }
                        else if(Email.isEmpty() && !First_name.isEmpty() && !Last_name.isEmpty() && age.isEmpty()){
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter your Age.\nPlease enter your Email.", "Error", JOptionPane.ERROR_MESSAGE);
    }
                  else if(Email.isEmpty() && !First_name.isEmpty() && !Last_name.isEmpty() && !age.isEmpty()){
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter your Email.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAgeLabel;
    private javax.swing.JTextField jAgeText;
    private javax.swing.JLabel jEmailLabel;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jFirstNameLablel;
    private javax.swing.JTextField jFirstNametext;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JTextField jLastNameText;
    private javax.swing.JLabel jMainlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSubmitButton;
    // End of variables declaration//GEN-END:variables
}
